/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package foods.myinterface;

import foods.dbonnection.Dbconnect;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import java.util.regex.* ;

/**
 *
 * @author Gajeendra
 */
public class main extends javax.swing.JFrame {

        Connection con= null;
        PreparedStatement pst = null;
        ResultSet rs = null;
    public main() {
        initComponents();
        
        con = Dbconnect.connec();
        
         tableload();
         tableload1();
         tableload2();
        
    }
    public void tableload(){
        
        try{
         
            String sql = "SELECT `Number`, `Date`, `Meal`, `Food`, `Quantam`, `Sname`, `Sid` FROM `order`";
            pst = con.prepareStatement(sql);
            rs =pst.executeQuery();
            
            table1.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e){
            
           System.out.println(e);
        }
        
        
        
        
    }
      public void tableload1(){
        
        try{
         
            String sql = "SELECT `Number1`, `Date1`, `Meal1`, `Food1`, `NumEmp`, `De1`, `De2`, `De3`, `De4`, `De5`, `De6`, `De7`, `De8` FROM `add`";
            pst = con.prepareStatement(sql);
            rs =pst.executeQuery();
            
            table2.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e){
            
           System.out.println(e);
        }
        
       
      }
      public void tableload2(){
        
        try{
         
            String sql = "SELECT `Rid`, `Rsname`, `Rsaddress`, `Rsphone`, `Remai` FROM `register`";
            pst = con.prepareStatement(sql);
            rs =pst.executeQuery();
            
            table3.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e){
            
           System.out.println(e);
        }
        
       
      }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        quantambox = new javax.swing.JTextField();
        snamebox = new javax.swing.JTextField();
        sidbox = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        meal2box = new javax.swing.JComboBox<>();
        food2box = new javax.swing.JComboBox<>();
        date2box = new com.toedter.calendar.JDateChooser();
        jLabel26 = new javax.swing.JLabel();
        numberbox = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        update1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        search1box = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        numemp1box = new javax.swing.JTextField();
        de2box = new javax.swing.JTextField();
        de1box = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        de4box = new javax.swing.JTextField();
        de3box = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        de5box = new javax.swing.JTextField();
        de6box = new javax.swing.JTextField();
        de7box = new javax.swing.JTextField();
        de8box = new javax.swing.JTextField();
        meal1box = new javax.swing.JComboBox<>();
        food1box = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        table2 = new javax.swing.JTable();
        jLabel25 = new javax.swing.JLabel();
        search1 = new javax.swing.JButton();
        deleteAdd = new javax.swing.JButton();
        update2 = new javax.swing.JButton();
        searchbox = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        clearAdd = new javax.swing.JButton();
        date1box = new com.toedter.calendar.JDateChooser();
        jLabel27 = new javax.swing.JLabel();
        number2box = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        Rsnamebox = new javax.swing.JTextField();
        Rsaddressbox = new javax.swing.JTextField();
        Rsphonebox = new javax.swing.JTextField();
        Remailbox = new javax.swing.JTextField();
        Radd = new javax.swing.JButton();
        Rclear = new javax.swing.JButton();
        aaa = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table3 = new javax.swing.JTable();
        Rdelete = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        RIDbox = new javax.swing.JLabel();
        Rupdate = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        rsearch = new javax.swing.JTextField();
        rseachs = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        check = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N

        jLabel1.setText("Date");

        jLabel2.setText("Meal");

        jLabel3.setText("Food");

        jLabel4.setText("Quantam");

        jLabel5.setText("Supplier Name");

        jLabel6.setText("Supplier Id");

        quantambox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantamboxActionPerformed(evt);
            }
        });
        quantambox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                quantamboxKeyTyped(evt);
            }
        });

        snamebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                snameboxActionPerformed(evt);
            }
        });
        snamebox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                snameboxKeyTyped(evt);
            }
        });

        sidbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sidboxActionPerformed(evt);
            }
        });

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "Date", "Meal", "Food", "Quantam", "Supplier Id", "Supplier id"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                table1MouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(table1);

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel8.setText("Foods and Beverage Department");

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel9.setText("Order Page");

        meal2box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Morning", "Lunch", "Dinner" }));

        food2box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rice", "Hoppers", "Kottu", "MilkRice" }));

        jLabel26.setText("Number");

        numberbox.setText("id");

        add.setText("Add / Send");
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
        });
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        update1.setText("Update");
        update1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update1ActionPerformed(evt);
            }
        });

        jLabel7.setText("Search");

        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        jButton5.setText("Delete");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel10.setText("(data is sent supply department and database)");

        jLabel28.setText("(auto generte)");

        jLabel37.setText("(yyyy-MM-dd)");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(57, 57, 57)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(date2box, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                                        .addComponent(quantambox, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(food2box, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(meal2box, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(snamebox))
                                    .addComponent(sidbox, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 849, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(update1))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(296, 296, 296)
                                .addComponent(jLabel37))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addGap(100, 100, 100)
                                .addComponent(numberbox, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel28))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(363, 363, 363)
                                .addComponent(jLabel8))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(add)
                                .addGap(290, 290, 290)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31)
                                        .addComponent(search1box, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(50, 50, 50)
                                        .addComponent(search)
                                        .addGap(39, 39, 39)
                                        .addComponent(jButton5))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(60, 60, 60)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addGap(45, 45, 45)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(numberbox)
                            .addComponent(jLabel28))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(date2box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(meal2box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(food2box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(quantambox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(snamebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(sidbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(75, 75, 75)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add)
                    .addComponent(clear)
                    .addComponent(update1)
                    .addComponent(jLabel7)
                    .addComponent(search1box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search)
                    .addComponent(jButton5))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel10))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel37)))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Order Page", jPanel1);

        jLabel11.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel11.setText("Foods and Beverage Department");

        jLabel12.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel12.setText("Add page");

        jLabel13.setText("Date");

        jLabel14.setText("Meal");

        jLabel15.setText("Food");

        jLabel16.setText("Number of employee");

        jLabel17.setText("Department 1");

        jLabel18.setText("Department 2");

        numemp1box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numemp1boxActionPerformed(evt);
            }
        });
        numemp1box.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numemp1boxKeyTyped(evt);
            }
        });

        de2box.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                de2boxKeyTyped(evt);
            }
        });

        de1box.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                de1boxKeyTyped(evt);
            }
        });

        jLabel19.setText("Department 3");

        jLabel20.setText("Department 4");

        jLabel21.setText("Department 5");

        de4box.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                de4boxKeyTyped(evt);
            }
        });

        de3box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                de3boxActionPerformed(evt);
            }
        });
        de3box.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                de3boxKeyTyped(evt);
            }
        });

        jLabel22.setText("Department 6");

        jLabel23.setText("Department 7");

        jLabel24.setText("Department 8");

        de5box.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                de5boxKeyTyped(evt);
            }
        });

        de6box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                de6boxActionPerformed(evt);
            }
        });
        de6box.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                de6boxKeyTyped(evt);
            }
        });

        de7box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                de7boxActionPerformed(evt);
            }
        });
        de7box.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                de7boxKeyTyped(evt);
            }
        });

        de8box.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                de8boxKeyTyped(evt);
            }
        });

        meal1box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Morning", "Lunch", "Dinner" }));

        food1box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rice", "Hoppers", "Kottu", "MilkRice" }));
        food1box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                food1boxActionPerformed(evt);
            }
        });

        table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Number", "Date", "Food", "Num of emp", "Kavinfu", "Department 2", "Department 3", "Department 4", "Department 5", "Department 6", "Department 7", "Department 8"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table2);

        jLabel25.setText("Search");

        search1.setText("Search");
        search1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search1ActionPerformed(evt);
            }
        });

        deleteAdd.setText("Delete");
        deleteAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAddActionPerformed(evt);
            }
        });

        update2.setText("Update");
        update2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update2ActionPerformed(evt);
            }
        });

        jButton9.setText("Add");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        clearAdd.setText("Clear");
        clearAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearAddActionPerformed(evt);
            }
        });

        jLabel27.setText("Number");

        number2box.setText("num");

        jLabel35.setText("(auto generte)");

        jLabel38.setText("(yyyy-MM-dd)");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(394, 394, 394)
                        .addComponent(jLabel11))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addGap(411, 411, 411)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(de1box, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(de2box, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(de3box, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(de4box, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(141, 141, 141)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel21)
                                            .addComponent(jLabel22)
                                            .addComponent(jLabel23)
                                            .addComponent(jLabel24))
                                        .addGap(85, 85, 85)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(de8box, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(de7box, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(de6box, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(de5box, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addGap(28, 28, 28)
                                .addComponent(searchbox, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(search1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(numemp1box, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(food1box, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                                .addComponent(jLabel13)
                                                .addGap(104, 104, 104))
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(jLabel14)
                                                .addGap(105, 105, 105)))
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(date1box, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(meal1box, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(number2box)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel35)))))
                                .addGap(70, 70, 70)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel20)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(136, 136, 136)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(21, 21, 21)
                                        .addComponent(update2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31)
                                        .addComponent(clearAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(deleteAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1031, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jLabel38)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel27)
                    .addComponent(number2box)
                    .addComponent(jLabel35))
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel17)
                                    .addComponent(de1box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(de5box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(date1box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel14)
                                .addComponent(de2box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(meal1box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel18))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(de6box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(food1box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(de3box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel23)
                        .addComponent(de7box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel19)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel20)
                    .addComponent(numemp1box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(de4box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(de8box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(update2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(clearAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(deleteAdd)))
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(search1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel38)
                .addGap(0, 156, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add page", jPanel3);

        jLabel29.setText("Supplier Name");

        jLabel30.setText("Supplier Address");

        jLabel31.setText("Supplier Phone Number");

        jLabel32.setText("Supplier Email");

        Rsnamebox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                RsnameboxKeyTyped(evt);
            }
        });

        Rsphonebox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                RsphoneboxKeyTyped(evt);
            }
        });

        Remailbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemailboxActionPerformed(evt);
            }
        });

        Radd.setText("Add");
        Radd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RaddActionPerformed(evt);
            }
        });

        Rclear.setText("Clear");
        Rclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RclearActionPerformed(evt);
            }
        });

        aaa.setText("aaa");

        table3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "name", "address", "phone", "email"
            }
        ));
        table3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(table3);

        Rdelete.setText("Delete");
        Rdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RdeleteActionPerformed(evt);
            }
        });

        jLabel33.setText("Number");

        RIDbox.setText("RID");

        Rupdate.setText("update");
        Rupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RupdateActionPerformed(evt);
            }
        });

        jLabel34.setText("Search");

        rseachs.setText("Search");
        rseachs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rseachsActionPerformed(evt);
            }
        });

        jLabel36.setText("(auto generte)");

        check.setText("check");
        check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel30)
                                    .addComponent(jLabel29)
                                    .addComponent(jLabel31)
                                    .addComponent(jLabel32)
                                    .addComponent(jLabel33)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(Radd)
                                        .addGap(36, 36, 36)
                                        .addComponent(Rclear)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Rsphonebox, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Remailbox, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Rsaddressbox, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Rsnamebox, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                            .addComponent(RIDbox, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel36)))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(Rdelete)
                                        .addGap(18, 18, 18)
                                        .addComponent(Rupdate))))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel34)
                                .addGap(18, 18, 18)
                                .addComponent(rsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rseachs)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(aaa, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 847, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(325, 325, 325)
                .addComponent(check)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel33)
                            .addComponent(RIDbox)
                            .addComponent(jLabel36))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Rsnamebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(Rsaddressbox, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Rsphonebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Remailbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel32))
                        .addGap(26, 26, 26)
                        .addComponent(aaa, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Radd)
                            .addComponent(Rclear)
                            .addComponent(Rdelete)
                            .addComponent(Rupdate))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel34)
                            .addComponent(rsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rseachs))
                        .addGap(37, 37, 37))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(check)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Supplier Reg", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 616, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void de3boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_de3boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_de3boxActionPerformed

    private void de6boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_de6boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_de6boxActionPerformed

    private void de7boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_de7boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_de7boxActionPerformed

    private void food1boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_food1boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_food1boxActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
  //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        SimpleDateFormat dateformat;
            dateformat = new SimpleDateFormat("yyyy-MM-dd");
        String date2 = dateformat.format(date2box.getDate());
        String meal2 = meal2box.getSelectedItem().toString();
        String food2 = food2box.getSelectedItem().toString();
        String quantam = quantambox.getText();
        String sname = snamebox.getText();
        String sid = sidbox.getText();
        
        
     try{
       String q = "INSERT INTO `order`( `Date`, `Meal`, `Food`, `Quantam`, `Sname`, `Sid`) VALUES ('"+date2+"','"+meal2+"','"+food2+"','"+quantam+"','"+sname+"','"+sid+"')";
       pst = con.prepareStatement(q);  
       pst.execute();
       
       tableload();
       
     }
     
     catch (Exception e)
     {
         System.out.println(e);
     }
  
  
  
  /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    }//GEN-LAST:event_addActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
   ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        SimpleDateFormat dateformat = new SimpleDateFormat("yyyy-MM-dd");
        String date1 = dateformat.format(date1box.getDate());
        String meal1 = meal1box.getSelectedItem().toString();
        String food1 = food1box.getSelectedItem().toString();
        String numEmp = numemp1box.getText();
        
        String dep1 = de1box.getText();
        String dep2 = de2box.getText();
        String dep3 = de3box.getText();
        String dep4 = de4box.getText();
        String dep5 = de5box.getText();
        String dep6 = de6box.getText();
        String dep7 = de7box.getText();
        String dep8 = de8box.getText();
        
        try{
           
            String p ="INSERT INTO `Add`(`Date1`, `Meal1`, `Food1`, `NumEmp`, `De1`, `De2`, `De3`, `De4`, `De5`, `De6`, `De7`, `De8`) VALUES ('"+date1+"','"+meal1+"','"+food1+"','"+numEmp+"','"+dep1+"','"+dep2+"','"+dep3+"','"+dep4+"','"+dep5+"','"+dep6+"','"+dep7+"','"+dep8+"') ";
            pst = con.prepareStatement(p);  
            pst.execute();
            tableload1();
        }
        catch(Exception e){
            
            System.out.println(e);
        }
        
        
        
   
   
   
   //////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9MouseClicked

    private void table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table1MouseClicked
               int q =table1.getSelectedRow();
        //DefaultTableModel model= (DefaultTableModel)date2box.getModel();
        
        
        String id = table1.getValueAt(q, 0).toString();
        Date date2; 
        try{
            date2 = new SimpleDateFormat("yyyy-MM-dd").parse(table1.getValueAt(q,1).toString());
            date2box.setDate(date2);
        }
        catch(Exception e){
            System.out.println(e);
        }
        String meal2 = table1.getValueAt(q, 2).toString();
        String food2 = table1.getValueAt(q, 3).toString();
        String quantam = table1.getValueAt(q, 4).toString();
        String sname = table1.getValueAt(q, 5).toString();
        String sid = table1.getValueAt(q, 6).toString();
        
        numberbox.setText(id);
       // date2box.setDate(date2);
        meal2box.setSelectedItem(meal2);
        food2box.setSelectedItem(food2);
        quantambox.setText(quantam);
        snamebox.setText(sname);
        sidbox.setText(sid);



////////////////////////////////////////////////////////////////////////////////////////////////////////////
    }//GEN-LAST:event_table1MouseClicked

    private void table1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_table1MouseEntered

    private void table2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table2MouseClicked
           int r = table2.getSelectedRow();
        //DefaultTableModel model= (DefaultTableModel)date2box.getModel();
        
        
        String  num= table2.getValueAt(r, 0).toString();
        Date date1; 
        try{
            date1 = new SimpleDateFormat("yyyy-MM-dd").parse(table2.getValueAt(r,1).toString());
            date1box.setDate(date1);
        }
        catch(Exception e){
            System.out.println(e);
        }
        String meal1 = table2.getValueAt(r, 2).toString();
        String food1 = table2.getValueAt(r, 3).toString();
        String numEmp = table2.getValueAt(r, 4).toString();
        String dep1 = table2.getValueAt(r, 5).toString();
        String dep2 = table2.getValueAt(r, 6).toString();
        String dep3 = table2.getValueAt(r, 6).toString();
        String dep4 = table2.getValueAt(r, 6).toString();
        String dep5 = table2.getValueAt(r, 6).toString();
        String dep6 = table2.getValueAt(r, 6).toString();
        String dep7 = table2.getValueAt(r, 6).toString();
        String dep8 = table2.getValueAt(r, 6).toString();
            
        
        number2box.setText(num);
      
        meal1box.setSelectedItem(meal1);
        food1box.setSelectedItem(food1);
        numemp1box.setText(numEmp);
        de1box.setText(dep1);
        de2box.setText(dep2);
        de3box.setText(dep3);
        de4box.setText(dep4);
        de5box.setText(dep5);
        de6box.setText(dep6);
        de7box.setText(dep7);
        de8box.setText(dep8);
         
   

        
        
        
        
        
        
        
    }//GEN-LAST:event_table2MouseClicked

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_addMouseClicked

    private void update1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update1ActionPerformed
       
        int x= JOptionPane.showConfirmDialog(null,"Do you really want to update");
        
        if(x==0){
            SimpleDateFormat dateformat;
            dateformat = new SimpleDateFormat("yyyy-MM-dd");
           
        String date2 = dateformat.format(date2box.getDate());
        String meal2 = meal2box.getSelectedItem().toString();
        String food2 = food2box.getSelectedItem().toString();
        String quantam = quantambox.getText();
        String sname = snamebox.getText();
        String sid = sidbox.getText();
        String id= numberbox.getText();
        
        String sql = "UPDATE `order` SET `Date`='"+date2+"',`Meal`='"+meal2+"',`Food`='"+food2+"',`Quantam`='"+quantam+"',`Sname`='"+sname+"',`Sid`='"+sid+"' where Number = '"+id +"'";
            try {  
                pst = con.prepareStatement(sql);
                pst.execute();
                 
            } catch (SQLException ex) {
                Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
            }
            tableload();
        }
        
        
        
        
    }//GEN-LAST:event_update1ActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
   
        
//        meal2box.setText("");
//        food2box.setText("");
        quantambox.setText("");
        snamebox.setText("");
        sidbox.setText("");
        
        
        
        
    }//GEN-LAST:event_clearActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

             int x= JOptionPane.showConfirmDialog(null,"Do you really want to delete");
        
        if(x==0){
         
        String id= numberbox.getText();
        
        String sql = "DELETE FROM `order` where Number = '"+id +"'";
            try {  
                pst = con.prepareStatement(sql);
                pst.execute();
                 
            } catch (SQLException ex) {
                Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
            }
            tableload();
        }
        
        
        
        
        
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed

        String num = search1box.getText();
        
        String sql="SELECT Number, Date, Meal, Food, Quantam, Sname, Sid FROM `order` WHERE Date = '"+num+"'";
        
        try{
         
            
            pst = con.prepareStatement(sql);
            rs =pst.executeQuery();
            
            table1.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e){
            
           System.out.println(e);
        }
        
        
    }//GEN-LAST:event_searchActionPerformed

    private void clearAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearAddActionPerformed
   
      
        numemp1box.setText("");
        de1box.setText("");
        de2box.setText("");
        de3box.setText("");
        de4box.setText("");
        de5box.setText("");
        de6box.setText("");
        de7box.setText("");
        de8box.setText("");
        
        
        
        
    }//GEN-LAST:event_clearAddActionPerformed

    private void update2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update2ActionPerformed
    
        int x= JOptionPane.showConfirmDialog(null,"Do you really want to update");
        String num2 = number2box.getText();
        if(x==0){
            SimpleDateFormat dateformat;
            dateformat = new SimpleDateFormat("yyyy-MM-dd");
        
         
        String date1 = dateformat.format(date1box.getDate());
        String meal1 = meal1box.getSelectedItem().toString();
        String food1 = food1box.getSelectedItem().toString();
        String numEmp = numemp1box.getText();
        
        String dep1 = de1box.getText();
        String dep2 = de2box.getText();
        String dep3 = de3box.getText();
        String dep4 = de4box.getText();
        String dep5 = de5box.getText();
        String dep6 = de6box.getText();
        String dep7 = de7box.getText();
        String dep8 = de8box.getText();
        
        try{
           
            String p ="UPDATE `add` SET `Date1`='"+date1+"',`Meal1`='"+meal1+"',`Food1`='"+food1+"',`NumEmp`='"+numEmp+"',`De1`='"+dep1+"',`De2`='"+dep2+"',`De3`='"+dep3+"',`De4`='"+dep4+"',`De5`='"+dep5+"',`De6`='"+dep6+"',`De7`='"+dep7+"',`De8`='"+dep8+"' where Number1 = '"+num2 +"'";
            pst = con.prepareStatement(p);  
            pst.execute();
            tableload1();
        }
        catch(Exception e){
            
            System.out.println(e);
        }
        
        }     
        
    }//GEN-LAST:event_update2ActionPerformed

    private void deleteAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAddActionPerformed
   
                int x= JOptionPane.showConfirmDialog(null,"Do you really want to delete");
        
        if(x==0){
         
        String id= number2box.getText();
        
        String sql = "DELETE FROM `add` WHERE Number1= '"+id+"'";
            try {  
                pst = con.prepareStatement(sql);
                pst.execute();
                 
            } catch (SQLException ex) {
                Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
            }
            tableload1();
        }
        
        
    }//GEN-LAST:event_deleteAddActionPerformed

    private void search1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search1ActionPerformed
        
        
        String num = searchbox.getText();
        
        
        String sql="SELECT Number1, Date1, Meal1, Food1, NumEmp, De1, De2, De3, De4, De5, De6, De7, De8 FROM `add` WHERE  Date1 = '"+num+"'";
        
        try{
         
            
            pst = con.prepareStatement(sql);
            rs =pst.executeQuery();
            
            table2.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e){
            
           System.out.println(e);
        }
        
        
    }//GEN-LAST:event_search1ActionPerformed

    private void RemailboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemailboxActionPerformed
       

    }//GEN-LAST:event_RemailboxActionPerformed

    private void RaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RaddActionPerformed
        
        String PHONE_PATTERN ="^\\d{10}$";
        Pattern pattern = Pattern.compile(PHONE_PATTERN);
        Matcher regexMatcher = pattern.matcher(Rsphonebox.getText());
        if(!regexMatcher.matches()){
            JOptionPane.showMessageDialog(null, "Number format is no valid");
            
            
          
        }
        else{
             JOptionPane.showMessageDialog(null, "Number format is  valid");
        
    
         String EMAIL_PATTERN ="[a-zA-z0-9]{1,20}@[a-zA-z0-9]{1,20}.[a-zA-z]{2,3}";
        pattern = Pattern.compile(EMAIL_PATTERN);
         regexMatcher = pattern.matcher(Remailbox.getText());
        if(!regexMatcher.matches()){
            JOptionPane.showMessageDialog(null, "Emaail format is no valid");
            
            
          
        }
        else{
             JOptionPane.showMessageDialog(null, "Emaail format is  valid");
               String rname = Rsnamebox.getText();
        String raddress = Rsaddressbox.getText();
        String rphone= Rsphonebox.getText();
        String remail = Remailbox.getText();
        
                try{
      String sql="INSERT INTO `register`(`Rsname`, `Rsaddress`, `Rsphone`, `Remai`) VALUES ('"+rname+"','"+raddress+"','"+rphone+"','"+remail+"')";
       pst = con.prepareStatement(sql);  
       pst.execute();
       
       tableload2();
       
     }
     
     catch (Exception e)
     {
         System.out.println(e);
     }
        
        
        }
      
        }
         
     
      
        
        
     
    }//GEN-LAST:event_RaddActionPerformed

    private void quantamboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantamboxActionPerformed
       
    }//GEN-LAST:event_quantamboxActionPerformed

    private void sidboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sidboxActionPerformed
      
    }//GEN-LAST:event_sidboxActionPerformed

    private void snameboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_snameboxActionPerformed
    
    }//GEN-LAST:event_snameboxActionPerformed

    private void numemp1boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numemp1boxActionPerformed
    
    }//GEN-LAST:event_numemp1boxActionPerformed

    private void quantamboxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quantamboxKeyTyped
       try {

            char c = evt.getKeyChar();
            if(!Character.isDigit(c))
            {
                evt.consume();
                Toolkit.getDefaultToolkit().beep();
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        } 
    }//GEN-LAST:event_quantamboxKeyTyped

    private void snameboxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_snameboxKeyTyped
        try {

            char c = evt.getKeyChar();
            if(!Character.isAlphabetic(c))
            {
                evt.consume();
                Toolkit.getDefaultToolkit().beep();
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        } 
    }//GEN-LAST:event_snameboxKeyTyped

    private void de1boxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_de1boxKeyTyped
         try {

            char c = evt.getKeyChar();
            if(!Character.isDigit(c))
            {
                evt.consume();
                Toolkit.getDefaultToolkit().beep();
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        } 
    }//GEN-LAST:event_de1boxKeyTyped

    private void de2boxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_de2boxKeyTyped
       try {

            char c = evt.getKeyChar();
            if(!Character.isDigit(c))
            {
                evt.consume();
                Toolkit.getDefaultToolkit().beep();
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        } 
    }//GEN-LAST:event_de2boxKeyTyped

    private void de3boxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_de3boxKeyTyped
        try {

            char c = evt.getKeyChar();
            if(!Character.isDigit(c))
            {
                evt.consume();
                Toolkit.getDefaultToolkit().beep();
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        } 
    }//GEN-LAST:event_de3boxKeyTyped

    private void de4boxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_de4boxKeyTyped
        try {

            char c = evt.getKeyChar();
            if(!Character.isDigit(c))
            {
                evt.consume();
                Toolkit.getDefaultToolkit().beep();
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        } 
    }//GEN-LAST:event_de4boxKeyTyped

    private void de5boxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_de5boxKeyTyped
      try {

            char c = evt.getKeyChar();
            if(!Character.isDigit(c))
            {
                evt.consume();
                Toolkit.getDefaultToolkit().beep();
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        } 
    }//GEN-LAST:event_de5boxKeyTyped

    private void de6boxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_de6boxKeyTyped
        try {

            char c = evt.getKeyChar();
            if(!Character.isDigit(c))
            {
                evt.consume();
                Toolkit.getDefaultToolkit().beep();
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        } 
    }//GEN-LAST:event_de6boxKeyTyped

    private void de7boxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_de7boxKeyTyped
        try {

            char c = evt.getKeyChar();
            if(!Character.isDigit(c))
            {
                evt.consume();
                Toolkit.getDefaultToolkit().beep();
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        } 
    }//GEN-LAST:event_de7boxKeyTyped

    private void de8boxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_de8boxKeyTyped
       try {

            char c = evt.getKeyChar();
            if(!Character.isDigit(c))
            {
                evt.consume();
                Toolkit.getDefaultToolkit().beep();
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        } 
    }//GEN-LAST:event_de8boxKeyTyped

    private void numemp1boxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numemp1boxKeyTyped
        try {

            char c = evt.getKeyChar();
            if(!Character.isDigit(c))
            {
                evt.consume();
                Toolkit.getDefaultToolkit().beep();
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        } 
    }//GEN-LAST:event_numemp1boxKeyTyped

    private void RclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RclearActionPerformed
        Rsnamebox.setText("");
        Rsaddressbox.setText("");
        Rsphonebox.setText("");
        Remailbox.setText("");
        
    }//GEN-LAST:event_RclearActionPerformed

    private void RdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdeleteActionPerformed
        int x= JOptionPane.showConfirmDialog(null,"Do you really want to delete");
        
        if(x==0){
         
        String RID= RIDbox.getText();
        
        String sql = "DELETE FROM `register` WHERE  Rid = '"+RID +"'";
            try {  
                pst = con.prepareStatement(sql);
                pst.execute();
                 
            } catch (SQLException ex) {
                Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
            }
            tableload2();
        }
        
        
        
    }//GEN-LAST:event_RdeleteActionPerformed

    private void table3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table3MouseClicked
                    int q =table3.getSelectedRow();
       
        
        
        
        
        String rname = table3.getValueAt(q, 1).toString();
        String raddress = table3.getValueAt(q, 2).toString();
        String rphone = table3.getValueAt(q, 3).toString();
        String remail = table3.getValueAt(q, 4).toString();
        String RID = table3.getValueAt(q, 0).toString();
        
        
       
        Rsnamebox.setText(rname);
        Rsaddressbox.setText(raddress);
        Rsphonebox.setText(rphone);
        Remailbox.setText(remail);
        RIDbox.setText(RID);


    }//GEN-LAST:event_table3MouseClicked

    private void RupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RupdateActionPerformed
       int x= JOptionPane.showConfirmDialog(null,"Do you really want to update");
        
        if(x==0){
            
           
        
        String rname = Rsnamebox.getText();
        String raddress = Rsaddressbox.getText();
        String rphone= Rsphonebox.getText();
         String remail= Remailbox.getText();
         String RID= RIDbox.getText();
        
        String sql = "UPDATE `register` SET `Rsname`='"+rname+"',`Rsaddress`='"+raddress+"',`Rsphone`='"+rphone+"',`Remai`='"+remail+"' WHERE  Rid = '"+RID +"'";
            try {  
                pst = con.prepareStatement(sql);
                pst.execute();
                 
            } catch (SQLException ex) {
                Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
            }
            tableload2();
        }
        
    }//GEN-LAST:event_RupdateActionPerformed

    private void rseachsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rseachsActionPerformed
          String name = rsearch.getText();
        
        String sql="SELECT Rid, Rsname, Rsaddress, Rsphone, Remai FROM `register` WHERE Rsname LIKE '%"+name+"%'";
        
        try{
         
            
            pst = con.prepareStatement(sql);
            rs =pst.executeQuery();
            
            table3.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e){
            
           System.out.println(e);
        }
        
        
    }//GEN-LAST:event_rseachsActionPerformed

    private void RsphoneboxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RsphoneboxKeyTyped
      try {

            char c = evt.getKeyChar();
            if(!Character.isDigit(c))
            {
                evt.consume();
                Toolkit.getDefaultToolkit().beep();
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        } 
    }//GEN-LAST:event_RsphoneboxKeyTyped

    private void RsnameboxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RsnameboxKeyTyped
        try {

            char c = evt.getKeyChar();
            if(!Character.isAlphabetic(c))
            {
                evt.consume();
                Toolkit.getDefaultToolkit().beep();
            }
            
        } catch (Exception e) {
        }   
    }//GEN-LAST:event_RsnameboxKeyTyped

    private void checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkActionPerformed
       String PHONE_PATTERN ="^\\d{10}$";
        Pattern pattern = Pattern.compile(PHONE_PATTERN);
        Matcher regexMatcher = pattern.matcher(Rsphonebox.getText());
        if(!regexMatcher.matches()){
            JOptionPane.showMessageDialog(null, "Number format is no valid");
            
            
          
        }
        else{
             JOptionPane.showMessageDialog(null, "Number format is  valid");
        }
        
            
      
    }//GEN-LAST:event_checkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new main().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel RIDbox;
    private javax.swing.JButton Radd;
    private javax.swing.JButton Rclear;
    private javax.swing.JButton Rdelete;
    private javax.swing.JTextField Remailbox;
    private javax.swing.JTextField Rsaddressbox;
    private javax.swing.JTextField Rsnamebox;
    private javax.swing.JTextField Rsphonebox;
    private javax.swing.JButton Rupdate;
    private javax.swing.JLabel aaa;
    private javax.swing.JButton add;
    private javax.swing.JButton check;
    private javax.swing.JButton clear;
    private javax.swing.JButton clearAdd;
    private com.toedter.calendar.JDateChooser date1box;
    private com.toedter.calendar.JDateChooser date2box;
    private javax.swing.JTextField de1box;
    private javax.swing.JTextField de2box;
    private javax.swing.JTextField de3box;
    private javax.swing.JTextField de4box;
    private javax.swing.JTextField de5box;
    private javax.swing.JTextField de6box;
    private javax.swing.JTextField de7box;
    private javax.swing.JTextField de8box;
    private javax.swing.JButton deleteAdd;
    private javax.swing.JComboBox<String> food1box;
    private javax.swing.JComboBox<String> food2box;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox<String> meal1box;
    private javax.swing.JComboBox<String> meal2box;
    private javax.swing.JLabel number2box;
    private javax.swing.JLabel numberbox;
    private javax.swing.JTextField numemp1box;
    private javax.swing.JTextField quantambox;
    private javax.swing.JButton rseachs;
    private javax.swing.JTextField rsearch;
    private javax.swing.JButton search;
    private javax.swing.JButton search1;
    private javax.swing.JTextField search1box;
    private javax.swing.JTextField searchbox;
    private javax.swing.JTextField sidbox;
    private javax.swing.JTextField snamebox;
    private javax.swing.JTable table1;
    private javax.swing.JTable table2;
    private javax.swing.JTable table3;
    private javax.swing.JButton update1;
    private javax.swing.JButton update2;
    // End of variables declaration//GEN-END:variables

}
