/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Export_Import;

import DbConnection.db;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.ResultSet;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Ravindu
 */
public class Export_Import extends javax.swing.JFrame {

    /**
     * Creates new form Export_Import
     */
    public Export_Import() {
        initComponents();
        
       
        
        try{
            
        
        Connection c = db.mycon();
        Statement s = c.createStatement();
        ResultSet rs1 = s.executeQuery("Select Type,Price from exportprices");
        exportTable.setModel(DbUtils.resultSetToTableModel(rs1));
        ResultSet rs2 = s.executeQuery("Select Type, Price from importprices");
        imprtTable.setModel(DbUtils.resultSetToTableModel(rs2));
        ResultSet rs3 = s.executeQuery("Select Company_name,Email_address,order_type,Quantity from customer where Customer_type = '"+"Foriegn customer"+"' ");
        CustomerDetails.setModel(DbUtils.resultSetToTableModel(rs3));
        ResultSet rs4 = s.executeQuery("Select Supplier,email,Type,Quantity from supplier_import ");
        supplierdetails.setModel(DbUtils.resultSetToTableModel(rs4));
        }
        catch(Exception e){
           // e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        ExportPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        expCmpn = new javax.swing.JTextField();
        expmail = new javax.swing.JTextField();
        expamnt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        exptype = new javax.swing.JTextField();
        dateChooserCombo1 = new datechooser.beans.DateChooserCombo();
        Tables = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        exportTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        expPlace = new javax.swing.JButton();
        expSendmail = new javax.swing.JButton();
        Insertexport = new javax.swing.JButton();
        resetexport = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        unitpriceexp = new javax.swing.JTextField();
        expcost = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        CustomerDetails = new javax.swing.JTable();
        jLabel23 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Export_Import_Panel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        imprtCmpny = new javax.swing.JTextField();
        imprtmail = new javax.swing.JTextField();
        imprtAmnt = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        imprttype = new javax.swing.JTextField();
        dateChooserCombo2 = new datechooser.beans.DateChooserCombo();
        Tables1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        imprtTable = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        imprtplace = new javax.swing.JButton();
        ImprtInsert = new javax.swing.JButton();
        resetimport = new javax.swing.JButton();
        imprtSendmail = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        imprtcost = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        supplierdetails = new javax.swing.JTable();
        jLabel26 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Export and Import Management");

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        ExportPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("Company Name");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("E-mail");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("Order Date");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setText("Amount");

        expCmpn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                expCmpnMouseClicked(evt);
            }
        });

        expmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                expmailMouseClicked(evt);
            }
        });

        expamnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expamntActionPerformed(evt);
            }
        });
        expamnt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                expamntKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setText("Type");

        exptype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exptypeActionPerformed(evt);
            }
        });
        exptype.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                exptypeKeyTyped(evt);
            }
        });

        dateChooserCombo1.setFormat(2);

        javax.swing.GroupLayout ExportPanelLayout = new javax.swing.GroupLayout(ExportPanel);
        ExportPanel.setLayout(ExportPanelLayout);
        ExportPanelLayout.setHorizontalGroup(
            ExportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ExportPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ExportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ExportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ExportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(expamnt, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                        .addComponent(exptype)
                        .addComponent(expmail)
                        .addComponent(expCmpn))
                    .addComponent(dateChooserCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        ExportPanelLayout.setVerticalGroup(
            ExportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ExportPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(ExportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(expCmpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ExportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(expmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ExportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateChooserCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ExportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exptype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ExportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(expamnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Tables.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel12.setText("Order Type");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel13.setText("Export");

        exportTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Item type", "Price"
            }
        ));
        exportTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exportTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(exportTable);
        if (exportTable.getColumnModel().getColumnCount() > 0) {
            exportTable.getColumnModel().getColumn(0).setHeaderValue("Item type");
            exportTable.getColumnModel().getColumn(1).setHeaderValue("Price");
        }

        jScrollPane2.setViewportView(jScrollPane3);

        javax.swing.GroupLayout TablesLayout = new javax.swing.GroupLayout(Tables);
        Tables.setLayout(TablesLayout);
        TablesLayout.setHorizontalGroup(
            TablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TablesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(TablesLayout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TablesLayout.setVerticalGroup(
            TablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TablesLayout.createSequentialGroup()
                .addGroup(TablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        expPlace.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        expPlace.setText("Place Order");
        expPlace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expPlaceActionPerformed(evt);
            }
        });

        expSendmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        expSendmail.setText("Send Mail");
        expSendmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expSendmailActionPerformed(evt);
            }
        });

        Insertexport.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Insertexport.setText("Insert");
        Insertexport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertexportActionPerformed(evt);
            }
        });

        resetexport.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        resetexport.setText("Reset");
        resetexport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetexportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(expPlace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(expSendmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Insertexport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(resetexport, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(Insertexport, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(expPlace, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(expSendmail, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(resetexport, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel21.setText("Unit Price");

        unitpriceexp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unitpriceexpActionPerformed(evt);
            }
        });
        unitpriceexp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                unitpriceexpKeyTyped(evt);
            }
        });

        expcost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expcostActionPerformed(evt);
            }
        });
        expcost.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                expcostKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setText("Cost Rs");

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Calculate");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel18.setText("Cargo Chargers ");

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField3KeyTyped(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel25.setText("Cost $");

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField4KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                            .addComponent(unitpriceexp)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81)
                        .addComponent(expcost))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jButton3))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel18))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unitpriceexp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(expcost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jButton3)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        CustomerDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Customer Name", "Email", "Type", "Amount"
            }
        ));
        CustomerDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CustomerDetailsMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(CustomerDetails);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setText("Customer Order Details");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ExportPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(Tables, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(10, 10, 10)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ExportPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Tables, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Export Orders", jPanel1);

        Export_Import_Panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel8.setText("Company Name");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel9.setText("E-mail");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel10.setText("Order Date");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel11.setText("Amount");

        imprtCmpny.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imprtCmpnyMouseClicked(evt);
            }
        });

        imprtmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imprtmailMouseClicked(evt);
            }
        });

        imprtAmnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imprtAmntActionPerformed(evt);
            }
        });
        imprtAmnt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                imprtAmntKeyTyped(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel17.setText("Type");

        imprttype.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                imprttypeKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout Export_Import_PanelLayout = new javax.swing.GroupLayout(Export_Import_Panel);
        Export_Import_Panel.setLayout(Export_Import_PanelLayout);
        Export_Import_PanelLayout.setHorizontalGroup(
            Export_Import_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Export_Import_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Export_Import_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Export_Import_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imprtAmnt)
                    .addComponent(imprttype)
                    .addComponent(imprtCmpny)
                    .addComponent(imprtmail)
                    .addGroup(Export_Import_PanelLayout.createSequentialGroup()
                        .addComponent(dateChooserCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 66, Short.MAX_VALUE)))
                .addContainerGap())
        );
        Export_Import_PanelLayout.setVerticalGroup(
            Export_Import_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Export_Import_PanelLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(Export_Import_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imprtCmpny, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Export_Import_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imprtmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Export_Import_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateChooserCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Export_Import_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imprttype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Export_Import_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imprtAmnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66))
        );

        Tables1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel16.setText("Order Type");

        imprtTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Type", "Price"
            }
        ));
        imprtTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imprtTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(imprtTable);

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel19.setText("Import");

        javax.swing.GroupLayout Tables1Layout = new javax.swing.GroupLayout(Tables1);
        Tables1.setLayout(Tables1Layout);
        Tables1Layout.setHorizontalGroup(
            Tables1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Tables1Layout.createSequentialGroup()
                .addGroup(Tables1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Tables1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Tables1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Tables1Layout.setVerticalGroup(
            Tables1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Tables1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Tables1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        imprtplace.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        imprtplace.setText("Place Order");
        imprtplace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imprtplaceActionPerformed(evt);
            }
        });

        ImprtInsert.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ImprtInsert.setText("Insert");
        ImprtInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImprtInsertActionPerformed(evt);
            }
        });

        resetimport.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        resetimport.setText("Reset");
        resetimport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetimportActionPerformed(evt);
            }
        });

        imprtSendmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        imprtSendmail.setText("Send Mail");
        imprtSendmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imprtSendmailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(imprtplace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ImprtInsert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(imprtSendmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(resetimport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ImprtInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(imprtplace, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(imprtSendmail, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(resetimport, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel22.setText("Unit Price");

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        imprtcost.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                imprtcostKeyTyped(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel15.setText("Cost");

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("Calculate");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel24.setText("Rs");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel14.setText("Cargo Chargers");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(imprtcost, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(63, 63, 63))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imprtcost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        supplierdetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "SupplierName", "Email", "Type", "Quantity"
            }
        ));
        supplierdetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                supplierdetailsMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(supplierdetails);

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel26.setText("Supplier order Details");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Tables1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Export_Import_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Export_Import_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(29, 29, 29)
                        .addComponent(Tables1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Import Orders", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void expamntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expamntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expamntActionPerformed

    private void imprtAmntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imprtAmntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imprtAmntActionPerformed

    private void expSendmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expSendmailActionPerformed
        // TODO add your handling code here:
        Email e = new Email();
        e.setVisible(true);
    }//GEN-LAST:event_expSendmailActionPerformed

    private void InsertexportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertexportActionPerformed
        // Enter Export Item Details
         try {
            //show confirm msg box

            if(!expCmpn.getText().isEmpty() &&  !expmail.getText().isEmpty()
                    && !expamnt.getText().isEmpty() && !exptype.getText().isEmpty() && !jTextField3.getText().isEmpty()){
                 int x = JOptionPane.showConfirmDialog(rootPane, "Do you want to save this Record ? ");    
                if (x == 0) {
               
                        Connection c = db.mycon();
                        Statement s = c.createStatement();
                       
                            
                        FormValidations fv = new FormValidations();
                        
                        //check validity about the inputs
                      
                       /* if(fv.isAlphaNumeric(expid.getText())== false){
                            expid.setText("Invalid");
                        }*/
                        
                         if(fv.validateEmail(expmail.getText())== false){
                             expmail.setText("Invalid");
                        }
                      /*  else if(fv.isNumeric(expamnt.getText())== false){
                            expamnt.setText("Invalid");
                        }*/
                        

                        
                        else{
                        Distribution d = new Distribution();
                        s.executeUpdate("INSERT INTO export_item (CompanyName,Email,OrderDate,type,Amount,Cost) values('" + expCmpn.getText() + "','"+expmail.getText()+"','" + dateChooserCombo1.getText() + "','"+exptype.getText()+"','"+expamnt.getText()+"','"+expcost.getText()+"')");
                        JOptionPane.showMessageDialog(rootPane, "record has been saved successfully");
                        ResultSet rs2 = s.executeQuery("Select ExportID from export_item");
                        
                        
                            //exportTable.setModel(DbUtils.resultSetToTableModel(rs));
                         //Clearall();
                         
                         
                      /* Double amnt = Double.parseDouble(expamnt.getText());
                        ResultSet q = s.executeQuery("Select Stock from export_item where Type = '"+exptype.getText()+"'");
                        String value = q.toString();
                        Double stckValue = Double.parseDouble(value);
                         //stckValue = stckValue - amnt;
                        
                        s.executeUpdate("Update export_item set Stock = '"+expamnt.getText()+"' where Type = '"+exptype.getText()+"'");
                        
                        ResultSet rs = s.executeQuery("Select * from export_item");
                        exportTable.setModel(DbUtils.resultSetToTableModel(rs));*/
                        }
                        
                        
                    } else if (x == 1) {
                        //Clearall();
                        //expid.setText("");
                        expCmpn.setText(""); 
                        expmail.setText("");
                        //expdate.setText("");
                        exptype.setText("");
                        expamnt.setText("");
               
                    }
            }
            else
            {
                JOptionPane.showMessageDialog(rootPane, "Fill Empty Fields");
            }

        } catch (Exception e) {
           // e.printStackTrace();
        }
        
    }//GEN-LAST:event_InsertexportActionPerformed

    private void resetexportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetexportActionPerformed
        // reset export Details
                //expid.setText("");
                expCmpn.setText(""); 
                expmail.setText("");
                //expdate.setText("");
                exptype.setText("");
                expamnt.setText("");
                unitpriceexp.setText("");
                jTextField3.setText("");
                jTextField4.setText("");
                expcost.setText("");
                        
    }//GEN-LAST:event_resetexportActionPerformed

    private void resetimportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetimportActionPerformed
        // reset import details
                //imprtid.setText("");
                imprtCmpny.setText(""); 
                imprtmail.setText("");
                //imprtdate.setText("");
                imprttype.setText("");
                imprtcost.setText("");
                jTextField1.setText("");
                jTextField2.setText("");
                imprtcost.setText("");
    }//GEN-LAST:event_resetimportActionPerformed

    private void imprtSendmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imprtSendmailActionPerformed
        // Email Interface
        
        Email e = new Email();
        e.setVisible(true);
        
        
    }//GEN-LAST:event_imprtSendmailActionPerformed

    private void exptypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exptypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exptypeActionPerformed

    private void ImprtInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImprtInsertActionPerformed
        // Insert import item details
        try {

            //show confirm msg box
            if(!imprtCmpny.getText().isEmpty() && !imprtmail.getText().isEmpty()
                    && !imprtAmnt.getText().isEmpty() && !imprttype.getText().isEmpty()&& !imprtcost.getText().isEmpty()){
            int x = JOptionPane.showConfirmDialog(rootPane, "Do you want to save this Record ? ");
            
            
            
            if (x == 0) {
               
                Connection c = db.mycon();
                Statement s = c.createStatement();
               
                //check validity about inputs
                 FormValidations fv = new FormValidations();
                 /*if(fv.isAlphaNumeric(imprtid.getText()) == false   ){
                     imprtid.setText("Invalid");
                     
                     
                 }*/
                  if(fv.validateEmail(imprtmail.getText())== false ){
                     imprtmail.setText("Ivalid");
            }
                 /*else if(fv.isNumeric(imprtAmnt.getText())== false){
                     imprtAmnt.setText("Invalid");
                 }*/
                 

                 else{
                s.executeUpdate("INSERT INTO import_item (CompanyName,Email,OrderDate,type,Amount,Cost) values('" + imprtCmpny.getText() + "','"+imprtmail.getText()+"','" + dateChooserCombo2.getText() + "','"+imprttype.getText()+"','"+imprtAmnt.getText()+"','"+imprtcost.getText()+"')");
                JOptionPane.showMessageDialog(rootPane, "record has been saved successfully");
                //ResultSet rs2 = s.executeQuery("Select * from import_item");
                //imprtTable.setModel(DbUtils.resultSetToTableModel(rs2));
               // Clearall();
                    
                 }
            } else if (x == 1) {
                //Clearall();
                //imprtid.setText("");
                imprtCmpny.setText(""); 
                imprtmail.setText("");
                //imprtdate.setText("");
                imprttype.setText("");
                imprtcost.setText("");
               
            }
        }
            else{
                JOptionPane.showMessageDialog(rootPane, "Fill Empty Fields");
            }

        } catch (Exception e) {
            //e.printStackTrace();
        }
    }//GEN-LAST:event_ImprtInsertActionPerformed

    private void imprtplaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imprtplaceActionPerformed
       if(!imprtCmpny.getText().isEmpty() && !imprtmail.getText().isEmpty()
                    && !imprtAmnt.getText().isEmpty() && !imprttype.getText().isEmpty()){
        this.dispose();
        Distribution d =new Distribution();
        d.setVisible(true);
       }
       else{
           JOptionPane.showMessageDialog(rootPane, "Fill Empty Fields");
       }
    }//GEN-LAST:event_imprtplaceActionPerformed

    private void expPlaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expPlaceActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
        Distribution d =new Distribution();
        d.setVisible(true);
        
        
    }//GEN-LAST:event_expPlaceActionPerformed

    private void unitpriceexpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unitpriceexpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unitpriceexpActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // Clculate import Items:
        if(!jTextField1.getText().isEmpty() && !jTextField2.getText().isEmpty()&& imprtcost.getText().isEmpty()){
            FormValidations fv = new FormValidations();
           
            if(fv.isNumeric(jTextField2.getText()) == false){
                jTextField2.setText("Invalid");
            }
            double cost = 0.00;
            double amnt;
            double unitp;
            double crgo;
            unitp = Double.parseDouble(jTextField1.getText());
            amnt = Double.parseDouble(imprtAmnt.getText());
            crgo = Double.parseDouble(jTextField2.getText());
            cost = amnt*unitp + crgo;
            String c = Double.toString(cost);
            imprtcost.setText(c);
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Fill Empty Fields");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Calculate Export Cost
        if(!unitpriceexp.getText().isEmpty()&& !jTextField3.getText().isEmpty()){
            FormValidations fv = new FormValidations();
            if(fv.isNumeric(jTextField3.getText())== false){
                jTextField3.setText("Invalid");
            }
            
            
            double cost = 0.00;
            double amnt;
            double unitp;
            double crgo ;
            double dollar = 152.50;
            unitp = Double.parseDouble(unitpriceexp.getText());
            amnt = Double.parseDouble(expamnt.getText());
            crgo = Double.parseDouble(jTextField3.getText());
            cost = amnt*unitp + crgo ;
            String c = Double.toString(cost);
            expcost.setText(c);
            double cost$ = cost/dollar;
            String c1 = Double.toString(cost$);
            jTextField4.setText(c1);
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Fill Empty Fields");
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void exportTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exportTableMouseClicked
        // Get Unit Prices
        int row = exportTable.getSelectedRow();
        String unitp = exportTable.getValueAt(row, 1).toString();
        unitpriceexp.setText(unitp);
    }//GEN-LAST:event_exportTableMouseClicked

    private void imprtTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imprtTableMouseClicked
        // Get Unit Prices :
        int row = imprtTable.getSelectedRow();
        String unitp = imprtTable.getValueAt(row, 1).toString();
        jTextField1.setText(unitp);
    }//GEN-LAST:event_imprtTableMouseClicked

    private void expcostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expcostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expcostActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void expamntKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_expamntKeyTyped
        // numeric values only
         try {

            char c = evt.getKeyChar();
            if(!Character.isDigit(c))
            {
                evt.consume();
                Toolkit.getDefaultToolkit().beep();
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }        
    }//GEN-LAST:event_expamntKeyTyped

    private void unitpriceexpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_unitpriceexpKeyTyped
        // numeric only
         try {

            char c = evt.getKeyChar();
            if(!Character.isDigit(c))
            {
                evt.consume();
                Toolkit.getDefaultToolkit().beep();
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }        
    }//GEN-LAST:event_unitpriceexpKeyTyped

    private void jTextField3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyTyped
        // numeric only
         try {

            char c = evt.getKeyChar();
            if(!Character.isDigit(c))
            {
                evt.consume();
                Toolkit.getDefaultToolkit().beep();
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }        
    }//GEN-LAST:event_jTextField3KeyTyped

    private void expcostKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_expcostKeyTyped
        // no user inputs
         try {

            char c = evt.getKeyChar();
            if(!Character.isDigit(c) || !Character.isAlphabetic(c))
            {
                evt.consume();
                Toolkit.getDefaultToolkit().beep();
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }        
    }//GEN-LAST:event_expcostKeyTyped

    private void jTextField4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyTyped
        // no user inputs
         try {

            char c = evt.getKeyChar();
            if(!Character.isDigit(c) || !Character.isAlphabetic(c))
            {
                evt.consume();
                Toolkit.getDefaultToolkit().beep();
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }        
    }//GEN-LAST:event_jTextField4KeyTyped

    private void exptypeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_exptypeKeyTyped
        // alphabetic values
         try {

            char c = evt.getKeyChar();
            if(!Character.isAlphabetic(c))
            {
                evt.consume();
                Toolkit.getDefaultToolkit().beep();
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }        
    }//GEN-LAST:event_exptypeKeyTyped

    private void imprttypeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_imprttypeKeyTyped
        // alphabets only
         try {

            char c = evt.getKeyChar();
            if(!Character.isAlphabetic(c))
            {
                evt.consume();
                Toolkit.getDefaultToolkit().beep();
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }        
    }//GEN-LAST:event_imprttypeKeyTyped

    private void imprtAmntKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_imprtAmntKeyTyped
        // numbers only
         try {

            char c = evt.getKeyChar();
            if(!Character.isDigit(c))
            {
                evt.consume();
                Toolkit.getDefaultToolkit().beep();
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }        
    }//GEN-LAST:event_imprtAmntKeyTyped

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        // numbers only
         try {

            char c = evt.getKeyChar();
            if(!Character.isDigit(c))
            {
                evt.consume();
                Toolkit.getDefaultToolkit().beep();
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }        
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyTyped
        //numbers only
         try {

            char c = evt.getKeyChar();
            if(!Character.isDigit(c))
            {
                evt.consume();
                Toolkit.getDefaultToolkit().beep();
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }        
    }//GEN-LAST:event_jTextField2KeyTyped

    private void imprtcostKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_imprtcostKeyTyped
        //no user inputs
         try {

            char c = evt.getKeyChar();
            if(!Character.isDigit(c) || !Character.isAlphabetic(c))
            {
                evt.consume();
                Toolkit.getDefaultToolkit().beep();
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }        
    }//GEN-LAST:event_imprtcostKeyTyped

    private void expCmpnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_expCmpnMouseClicked
        // SetText
        expCmpn.setText("");
    }//GEN-LAST:event_expCmpnMouseClicked

    private void expmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_expmailMouseClicked
        // SetText
        expmail.setText("");
    }//GEN-LAST:event_expmailMouseClicked

    private void imprtCmpnyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imprtCmpnyMouseClicked
        // SetText
        imprtCmpny.setText("");
    }//GEN-LAST:event_imprtCmpnyMouseClicked

    private void imprtmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imprtmailMouseClicked
        // SetText
        imprtmail.setText("");
    }//GEN-LAST:event_imprtmailMouseClicked

    private void CustomerDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustomerDetailsMouseClicked
        int row = CustomerDetails.getSelectedRow();
        String custName = CustomerDetails.getValueAt(row, 0).toString();
        String custEmail = CustomerDetails.getValueAt(row, 1).toString();
        String custAmnt = CustomerDetails.getValueAt(row, 3).toString();
        String custType = CustomerDetails.getValueAt(row, 2).toString();
        expCmpn.setText(custName);
        expmail.setText(custEmail);
        expamnt.setText(custAmnt);
        exptype.setText(custType);
        
    }//GEN-LAST:event_CustomerDetailsMouseClicked

    private void supplierdetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplierdetailsMouseClicked
        // TODO add your handling code here:
        int row = supplierdetails.getSelectedRow();
        String suppName = supplierdetails.getValueAt(row, 0).toString();
        String suppEmail = supplierdetails.getValueAt(row, 1).toString();
        String suppAmnt = supplierdetails.getValueAt(row, 3).toString();
        String suppType = supplierdetails.getValueAt(row, 2).toString();
        imprtCmpny.setText(suppName);
        imprtmail.setText(suppEmail);
        imprtAmnt.setText(suppAmnt);
        imprttype.setText(suppType);
    }//GEN-LAST:event_supplierdetailsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Export_Import.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Export_Import.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Export_Import.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Export_Import.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Export_Import().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable CustomerDetails;
    private javax.swing.JPanel ExportPanel;
    private javax.swing.JPanel Export_Import_Panel;
    private javax.swing.JButton ImprtInsert;
    private javax.swing.JButton Insertexport;
    private javax.swing.JPanel Tables;
    private javax.swing.JPanel Tables1;
    public static datechooser.beans.DateChooserCombo dateChooserCombo1;
    public static datechooser.beans.DateChooserCombo dateChooserCombo2;
    public static javax.swing.JTextField expCmpn;
    private javax.swing.JButton expPlace;
    private javax.swing.JButton expSendmail;
    public static javax.swing.JTextField expamnt;
    private javax.swing.JTextField expcost;
    public static javax.swing.JTextField expmail;
    private javax.swing.JTable exportTable;
    public static javax.swing.JTextField exptype;
    public static javax.swing.JTextField imprtAmnt;
    public static javax.swing.JTextField imprtCmpny;
    private javax.swing.JButton imprtSendmail;
    private javax.swing.JTable imprtTable;
    public static javax.swing.JTextField imprtcost;
    public static javax.swing.JTextField imprtmail;
    private javax.swing.JButton imprtplace;
    public static javax.swing.JTextField imprttype;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    public static javax.swing.JTextField jTextField4;
    private javax.swing.JButton resetexport;
    private javax.swing.JButton resetimport;
    private javax.swing.JTable supplierdetails;
    private javax.swing.JTextField unitpriceexp;
    // End of variables declaration//GEN-END:variables
}
